package com.movtery.zalithlauncher.ui.activities

import android.system.Os
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.widthIn
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Slider
import androidx.compose.material3.Surface
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableLongStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.movtery.zalithlauncher.bridge.ZLBridge
import com.movtery.zalithlauncher.setting.AllSettings
import kotlinx.coroutines.delay
import kotlin.math.roundToInt

private fun applyFrameGenRuntimeSettings() {
    runCatching {
        Os.setenv("POJAV_FRAMEGEN_ENABLED", if (AllSettings.frameGenEnabled.state) "1" else "0", true)
        Os.setenv("POJAV_FRAMEGEN_PROFILE", AllSettings.frameGenProfile.state, true)
        Os.setenv("POJAV_FRAMEGEN_MULTIPLIER", AllSettings.frameGenMultiplier.state.toString(), true)
        Os.setenv("POJAV_FRAMEGEN_TARGET_FPS", AllSettings.frameGenTargetFps.state.toString(), true)
        Os.setenv("POJAV_FRAMEGEN_LOW_LATENCY", if (AllSettings.frameGenLowLatency.state) "1" else "0", true)
        Os.setenv("POJAV_FRAMEGEN_SCENE_PROTECTION", if (AllSettings.frameGenSceneProtection.state) "1" else "0", true)
    }
}

@Composable
fun FrameGenInGameOverlay() {
    var expanded by remember { mutableStateOf(false) }
    var realFps by remember { mutableIntStateOf(0) }
    var generatedFps by remember { mutableIntStateOf(0) }
    var presentedFps by remember { mutableIntStateOf(0) }
    var lastReal by remember { mutableLongStateOf(0L) }
    var lastGenerated by remember { mutableLongStateOf(0L) }
    var lastPresented by remember { mutableLongStateOf(0L) }

    val enabled = AllSettings.frameGenEnabled.state
    val profile = AllSettings.frameGenProfile.state
    val multiplier = AllSettings.frameGenMultiplier.state
    val targetFps = AllSettings.frameGenTargetFps.state
    val lowLatency = AllSettings.frameGenLowLatency.state
    val sceneProtection = AllSettings.frameGenSceneProtection.state
    val showHud = AllSettings.frameGenHud.state

    LaunchedEffect(enabled, profile, multiplier, targetFps, lowLatency, sceneProtection) {
        applyFrameGenRuntimeSettings()
    }

    LaunchedEffect(Unit) {
        while (true) {
            delay(1000)
            val stats = runCatching { ZLBridge.getFrameGenStats() }.getOrNull()
            if (stats != null && stats.size >= 4) {
                val r = stats[1]
                val g = stats[2]
                val p = stats[3]
                realFps = (r - lastReal).coerceAtLeast(0L).coerceAtMost(999L).toInt()
                generatedFps = (g - lastGenerated).coerceAtLeast(0L).coerceAtMost(999L).toInt()
                presentedFps = (p - lastPresented).coerceAtLeast(0L).coerceAtMost(999L).toInt()
                lastReal = r
                lastGenerated = g
                lastPresented = p
            }
        }
    }

    Box(
        modifier = Modifier.fillMaxSize(),
        contentAlignment = Alignment.TopEnd
    ) {
        Column(
            modifier = Modifier.padding(10.dp),
            horizontalAlignment = Alignment.End,
            verticalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            if (showHud) {
                Surface(
                    tonalElevation = 6.dp,
                    shape = MaterialTheme.shapes.medium
                ) {
                    Text(
                        modifier = Modifier.padding(horizontal = 10.dp, vertical = 6.dp),
                        text = "FG " + (if (enabled) "ON" else "OFF") +
                            "  Real " + realFps +
                            "  Gen " + generatedFps +
                            "  Out " + presentedFps,
                        style = MaterialTheme.typography.labelMedium
                    )
                }
            }

            Button(onClick = { expanded = !expanded }) {
                Text(if (expanded) "Fechar FG" else "FG")
            }

            if (expanded) {
                Card(modifier = Modifier.widthIn(min = 250.dp, max = 330.dp)) {
                    Column(
                        modifier = Modifier.padding(14.dp),
                        verticalArrangement = Arrangement.spacedBy(10.dp)
                    ) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Text("Frame Generation", modifier = Modifier.weight(1f))
                            Switch(
                                checked = enabled,
                                onCheckedChange = { AllSettings.frameGenEnabled.save(it) }
                            )
                        }

                        Text("Perfil: " + profile)
                        Row(horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                            Button(onClick = { AllSettings.frameGenProfile.save("performance") }) { Text("Perf.") }
                            Button(onClick = { AllSettings.frameGenProfile.save("balanced") }) { Text("Bal.") }
                            Button(onClick = { AllSettings.frameGenProfile.save("quality") }) { Text("Qual.") }
                        }

                        Text("Multiplicador: " + multiplier + "x")
                        Slider(
                            value = multiplier.toFloat(),
                            onValueChange = { AllSettings.frameGenMultiplier.save(it.roundToInt().coerceIn(2, 4)) },
                            valueRange = 2f..4f,
                            steps = 1
                        )

                        Text("FPS alvo: " + targetFps)
                        Slider(
                            value = targetFps.toFloat(),
                            onValueChange = {
                                val snapped = (it / 10f).roundToInt() * 10
                                AllSettings.frameGenTargetFps.save(snapped.coerceIn(30, 120))
                            },
                            valueRange = 30f..120f,
                            steps = 8
                        )

                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Text("Baixa latência", modifier = Modifier.weight(1f))
                            Switch(
                                checked = lowLatency,
                                onCheckedChange = { AllSettings.frameGenLowLatency.save(it) }
                            )
                        }

                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Text("Proteção de cena", modifier = Modifier.weight(1f))
                            Switch(
                                checked = sceneProtection,
                                onCheckedChange = { AllSettings.frameGenSceneProtection.save(it) }
                            )
                        }

                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Text("HUD", modifier = Modifier.weight(1f))
                            Switch(
                                checked = showHud,
                                onCheckedChange = { AllSettings.frameGenHud.save(it) }
                            )
                        }
                    }
                }
            }
        }
    }
}
